variable "namespace" {}
variable "region" {}
variable "vpc_cidr" {}
variable "pubnets" {}
variable "az_names" {}
variable "key" {}
variable "size" {}
variable "ami" {}
variable "vol_size" {}
variable "vol_type" {}
variable "zone" {}
variable "domain" {}
variable "bucket_name" {}
variable "acl" {}
variable "world_pass" {}
variable "world_display" {}
variable "world_name" {}
variable "game_data" {}
variable "app_id" {}
variable "tags" {}
